package ReyesKainan;

import java.awt.Component;
import java.awt.TextField;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;
/**
 *
 * @author Reyes Fam
 */
public class ReyesBarbs extends javax.swing.JFrame {

    /**
     * Creates new form ReyesBarbs
     */
    public ReyesBarbs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        checkOutBTN = new javax.swing.JButton();
        clearAllBTN = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        recieptDisplay = new java.awt.TextArea();
        refreshmentPNL = new javax.swing.JPanel();
        sprite = new javax.swing.JLabel();
        drinkTITLE = new javax.swing.JLabel();
        coke = new javax.swing.JLabel();
        icedTea = new javax.swing.JLabel();
        pineappleDrink = new javax.swing.JLabel();
        rootBeer = new javax.swing.JLabel();
        spriteFIELD = new javax.swing.JTextField();
        cokeFIELD = new javax.swing.JTextField();
        icedTeaFIELD = new javax.swing.JTextField();
        pineappleDrinkFIELD = new javax.swing.JTextField();
        rootBeerFIELD = new javax.swing.JTextField();
        icedTea1 = new javax.swing.JLabel();
        icedTea2 = new javax.swing.JLabel();
        icedTea3 = new javax.swing.JLabel();
        icedTea4 = new javax.swing.JLabel();
        icedTea5 = new javax.swing.JLabel();
        mealPNL = new javax.swing.JPanel();
        liempo = new javax.swing.JLabel();
        porkSisig = new javax.swing.JLabel();
        barbeque = new javax.swing.JLabel();
        javaRice = new javax.swing.JLabel();
        plainRice = new javax.swing.JLabel();
        plainRiceFIELD = new javax.swing.JTextField();
        javaRiceFIELD = new javax.swing.JTextField();
        barbequeFIELD = new javax.swing.JTextField();
        porkSisigFIELD = new javax.swing.JTextField();
        liempoFIELD = new javax.swing.JTextField();
        mealsTITLE = new javax.swing.JLabel();
        plainRice1 = new javax.swing.JLabel();
        plainRice2 = new javax.swing.JLabel();
        plainRice3 = new javax.swing.JLabel();
        plainRice4 = new javax.swing.JLabel();
        plainRice5 = new javax.swing.JLabel();
        reciptBTN = new javax.swing.JPanel();
        recipt = new javax.swing.JButton();
        costsPNL = new javax.swing.JPanel();
        costofMeal = new javax.swing.JLabel();
        costofDrinks = new javax.swing.JLabel();
        totalcostMade = new javax.swing.JLabel();
        totalCostMadeFIELD = new javax.swing.JTextField();
        CostofDrinksField = new javax.swing.JTextField();
        CostofMealFIELD = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        totalPNL = new javax.swing.JPanel();
        taxFIELD = new javax.swing.JTextField();
        subTotalFIELD = new javax.swing.JTextField();
        totalFIELD = new javax.swing.JTextField();
        taxLabel = new javax.swing.JLabel();
        subTotalLabel = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 5));
        jPanel2.setForeground(new java.awt.Color(255, 153, 0));

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\Downloads\\barbsTiny.png")); // NOI18N
        jPanel2.add(jLabel3);

        jLabel1.setFont(new java.awt.Font("Goudy Old Style", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reyes Barbeque");
        jPanel2.add(jLabel1);

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Downloads\\sisigTiny.png")); // NOI18N
        jPanel2.add(jLabel2);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 130));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        checkOutBTN.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        checkOutBTN.setText("CHECK OUT");
        checkOutBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutBTNActionPerformed(evt);
            }
        });

        clearAllBTN.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        clearAllBTN.setText("CLEAR ALL");
        clearAllBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearAllBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(checkOutBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 412, Short.MAX_VALUE)
                .addComponent(clearAllBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkOutBTN)
                    .addComponent(clearAllBTN))
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 750, 1030, 50));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        recieptDisplay.setEditable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(recieptDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(recieptDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 130, 360, 530));

        refreshmentPNL.setBackground(new java.awt.Color(153, 153, 153));
        refreshmentPNL.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        sprite.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        sprite.setForeground(new java.awt.Color(255, 255, 255));
        sprite.setText("Sprite in Can");

        drinkTITLE.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 48)); // NOI18N
        drinkTITLE.setForeground(new java.awt.Color(255, 255, 255));
        drinkTITLE.setText("Refreshments");

        coke.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        coke.setForeground(new java.awt.Color(255, 255, 255));
        coke.setText("Coke  in Can");

        icedTea.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        icedTea.setForeground(new java.awt.Color(255, 255, 255));
        icedTea.setText("Iced Tea");

        pineappleDrink.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        pineappleDrink.setForeground(new java.awt.Color(255, 255, 255));
        pineappleDrink.setText("Pinapple Drink");

        rootBeer.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        rootBeer.setForeground(new java.awt.Color(255, 255, 255));
        rootBeer.setText("Root Beer");

        spriteFIELD.setText("0");
        spriteFIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spriteFIELDActionPerformed(evt);
            }
        });

        cokeFIELD.setText("0");

        icedTeaFIELD.setText("0");

        pineappleDrinkFIELD.setText("0");
        pineappleDrinkFIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pineappleDrinkFIELDActionPerformed(evt);
            }
        });

        rootBeerFIELD.setText("0");

        icedTea1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        icedTea1.setForeground(new java.awt.Color(255, 255, 255));
        icedTea1.setText("........37.0");

        icedTea2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        icedTea2.setForeground(new java.awt.Color(255, 255, 255));
        icedTea2.setText("........35.0");

        icedTea3.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        icedTea3.setForeground(new java.awt.Color(255, 255, 255));
        icedTea3.setText("................40.0");

        icedTea4.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        icedTea4.setForeground(new java.awt.Color(255, 255, 255));
        icedTea4.setText("......36.0");

        icedTea5.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        icedTea5.setForeground(new java.awt.Color(255, 255, 255));
        icedTea5.setText("............45.0");

        javax.swing.GroupLayout refreshmentPNLLayout = new javax.swing.GroupLayout(refreshmentPNL);
        refreshmentPNL.setLayout(refreshmentPNLLayout);
        refreshmentPNLLayout.setHorizontalGroup(
            refreshmentPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, refreshmentPNLLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(drinkTITLE)
                .addGap(129, 129, 129))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, refreshmentPNLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(refreshmentPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, refreshmentPNLLayout.createSequentialGroup()
                        .addComponent(icedTea, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(icedTea3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(icedTeaFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(refreshmentPNLLayout.createSequentialGroup()
                        .addGroup(refreshmentPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(coke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sprite, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(refreshmentPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(refreshmentPNLLayout.createSequentialGroup()
                                .addComponent(icedTea1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spriteFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(refreshmentPNLLayout.createSequentialGroup()
                                .addComponent(icedTea2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cokeFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(refreshmentPNLLayout.createSequentialGroup()
                        .addComponent(pineappleDrink)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(icedTea4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pineappleDrinkFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, refreshmentPNLLayout.createSequentialGroup()
                        .addComponent(rootBeer, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(icedTea5, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rootBeerFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );
        refreshmentPNLLayout.setVerticalGroup(
            refreshmentPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(refreshmentPNLLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(drinkTITLE)
                .addGap(37, 37, 37)
                .addGroup(refreshmentPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spriteFIELD)
                    .addGroup(refreshmentPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sprite, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(icedTea1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(refreshmentPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(coke, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cokeFIELD, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(icedTea2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(refreshmentPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(refreshmentPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(icedTea, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(icedTea3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(icedTeaFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(refreshmentPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(refreshmentPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pineappleDrink, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(icedTea4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(pineappleDrinkFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(refreshmentPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rootBeer, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(refreshmentPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rootBeerFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(icedTea5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(refreshmentPNL, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 440, 470));

        mealPNL.setBackground(new java.awt.Color(153, 153, 153));
        mealPNL.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        liempo.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        liempo.setForeground(new java.awt.Color(255, 255, 255));
        liempo.setText("Liempo");

        porkSisig.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        porkSisig.setForeground(new java.awt.Color(255, 255, 255));
        porkSisig.setText("Pork Sisig");

        barbeque.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        barbeque.setForeground(new java.awt.Color(255, 255, 255));
        barbeque.setText("Barbeque");

        javaRice.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        javaRice.setForeground(new java.awt.Color(255, 255, 255));
        javaRice.setText("Java Rice");

        plainRice.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        plainRice.setForeground(new java.awt.Color(255, 255, 255));
        plainRice.setText("Plain Rice");

        plainRiceFIELD.setText("0");
        plainRiceFIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plainRiceFIELDActionPerformed(evt);
            }
        });

        javaRiceFIELD.setText("0");

        barbequeFIELD.setText("0");

        porkSisigFIELD.setText("0");
        porkSisigFIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porkSisigFIELDActionPerformed(evt);
            }
        });

        liempoFIELD.setText("0");

        mealsTITLE.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 48)); // NOI18N
        mealsTITLE.setForeground(new java.awt.Color(255, 255, 255));
        mealsTITLE.setText("Meals");

        plainRice1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        plainRice1.setForeground(new java.awt.Color(255, 255, 255));
        plainRice1.setText("............... 20.0");

        plainRice2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        plainRice2.setForeground(new java.awt.Color(255, 255, 255));
        plainRice2.setText("................45.0");

        plainRice3.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        plainRice3.setForeground(new java.awt.Color(255, 255, 255));
        plainRice3.setText("..............145.0");

        plainRice4.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        plainRice4.setForeground(new java.awt.Color(255, 255, 255));
        plainRice4.setText("...............65.0");

        plainRice5.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        plainRice5.setForeground(new java.awt.Color(255, 255, 255));
        plainRice5.setText(".................165.0");

        javax.swing.GroupLayout mealPNLLayout = new javax.swing.GroupLayout(mealPNL);
        mealPNL.setLayout(mealPNLLayout);
        mealPNLLayout.setHorizontalGroup(
            mealPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mealPNLLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(mealPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mealPNLLayout.createSequentialGroup()
                        .addComponent(liempo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(mealPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mealPNLLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(mealsTITLE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mealPNLLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(plainRice5, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6))))
                    .addGroup(mealPNLLayout.createSequentialGroup()
                        .addGroup(mealPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mealPNLLayout.createSequentialGroup()
                                .addComponent(plainRice)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(plainRice1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mealPNLLayout.createSequentialGroup()
                                .addComponent(javaRice)
                                .addGap(12, 12, 12)
                                .addComponent(plainRice2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mealPNLLayout.createSequentialGroup()
                                .addGroup(mealPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(barbeque, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(porkSisig))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mealPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(plainRice3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(plainRice4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(6, 6, 6)))
                .addGroup(mealPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(liempoFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(porkSisigFIELD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barbequeFIELD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(javaRiceFIELD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plainRiceFIELD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );
        mealPNLLayout.setVerticalGroup(
            mealPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mealPNLLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(mealsTITLE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(mealPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(plainRiceFIELD)
                    .addGroup(mealPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(plainRice, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(plainRice1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(mealPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(mealPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(javaRice, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(plainRice2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(javaRiceFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mealPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mealPNLLayout.createSequentialGroup()
                        .addGroup(mealPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(barbeque, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(barbequeFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(mealPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(porkSisig, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(porkSisigFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mealPNLLayout.createSequentialGroup()
                        .addComponent(plainRice4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(plainRice3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(mealPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(mealPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(liempo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(plainRice5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(liempoFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );

        getContentPane().add(mealPNL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 590, 470));

        reciptBTN.setBackground(new java.awt.Color(153, 153, 153));
        reciptBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        recipt.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        recipt.setText("PRINT RECIPT");
        recipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reciptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout reciptBTNLayout = new javax.swing.GroupLayout(reciptBTN);
        reciptBTN.setLayout(reciptBTNLayout);
        reciptBTNLayout.setHorizontalGroup(
            reciptBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reciptBTNLayout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addComponent(recipt)
                .addGap(113, 113, 113))
        );
        reciptBTNLayout.setVerticalGroup(
            reciptBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reciptBTNLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(recipt)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        getContentPane().add(reciptBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 660, 360, 140));

        costsPNL.setBackground(new java.awt.Color(153, 153, 153));
        costsPNL.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        costofMeal.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        costofMeal.setForeground(new java.awt.Color(255, 255, 255));
        costofMeal.setText("Total Cost on Meals");

        costofDrinks.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        costofDrinks.setForeground(new java.awt.Color(255, 255, 255));
        costofDrinks.setText("Total Cost on Refreshments");

        totalcostMade.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        totalcostMade.setForeground(new java.awt.Color(255, 255, 255));
        totalcostMade.setText("Total Cost Made");

        totalCostMadeFIELD.setEditable(false);

        CostofDrinksField.setEditable(false);
        CostofDrinksField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CostofDrinksFieldActionPerformed(evt);
            }
        });

        CostofMealFIELD.setEditable(false);
        CostofMealFIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CostofMealFIELDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout costsPNLLayout = new javax.swing.GroupLayout(costsPNL);
        costsPNL.setLayout(costsPNLLayout);
        costsPNLLayout.setHorizontalGroup(
            costsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, costsPNLLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(costsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(costofDrinks)
                    .addComponent(totalcostMade)
                    .addComponent(costofMeal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addGroup(costsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalCostMadeFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CostofDrinksField, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CostofMealFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );
        costsPNLLayout.setVerticalGroup(
            costsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(costsPNLLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(costsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(costofMeal, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(CostofMealFIELD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(costsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CostofDrinksField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(costofDrinks, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(costsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalCostMadeFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalcostMade, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        getContentPane().add(costsPNL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 590, 150));

        jPanel9.setBackground(new java.awt.Color(153, 153, 153));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 586, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 146, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 590, 150));

        totalPNL.setBackground(new java.awt.Color(153, 153, 153));
        totalPNL.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        taxFIELD.setEditable(false);
        taxFIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxFIELDActionPerformed(evt);
            }
        });

        subTotalFIELD.setEditable(false);

        totalFIELD.setEditable(false);
        totalFIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalFIELDActionPerformed(evt);
            }
        });

        taxLabel.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        taxLabel.setForeground(new java.awt.Color(255, 255, 255));
        taxLabel.setText("Tax");

        subTotalLabel.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        subTotalLabel.setForeground(new java.awt.Color(255, 255, 255));
        subTotalLabel.setText("SubTotal");

        totalLabel.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        totalLabel.setForeground(new java.awt.Color(255, 255, 255));
        totalLabel.setText("Total");

        javax.swing.GroupLayout totalPNLLayout = new javax.swing.GroupLayout(totalPNL);
        totalPNL.setLayout(totalPNLLayout);
        totalPNLLayout.setHorizontalGroup(
            totalPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, totalPNLLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(totalPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(taxLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subTotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addGroup(totalPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subTotalFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taxFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );
        totalPNLLayout.setVerticalGroup(
            totalPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalPNLLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(totalPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(taxLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(taxFIELD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(totalPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subTotalFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subTotalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(totalPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        getContentPane().add(totalPNL, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 600, 440, 150));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clearAllBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearAllBTNActionPerformed
       JTextField clear = null;
    
    for(Component c:mealPNL.getComponents()){
        if(c.getClass().toString().contains("javax.swing.JTextField")){
            clear = (JTextField)c;
            clear.setText("0");
            
        } 
    }   
    for(Component c:refreshmentPNL.getComponents()){
        if(c.getClass().toString().contains("javax.swing.JTextField")){
            clear = (JTextField)c;
            clear.setText("0");
            
        } 
    }
    for(Component c:costsPNL.getComponents()){
        if(c.getClass().toString().contains("javax.swing.JTextField")){
            clear = (JTextField)c;
            clear.setText("");
            
        } 
    }   
    for(Component c:totalPNL.getComponents()){
        if(c.getClass().toString().contains("javax.swing.JTextField")){
            clear = (JTextField)c;
            clear.setText("");
            
        } 
    }    
    recieptDisplay.setText(null);
    }//GEN-LAST:event_clearAllBTNActionPerformed

    private void totalFIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalFIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalFIELDActionPerformed

    private void spriteFIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spriteFIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spriteFIELDActionPerformed

    private void plainRiceFIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plainRiceFIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plainRiceFIELDActionPerformed

    private void CostofMealFIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CostofMealFIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CostofMealFIELDActionPerformed

    private void CostofDrinksFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CostofDrinksFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CostofDrinksFieldActionPerformed

    private void taxFIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxFIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taxFIELDActionPerformed

    private void pineappleDrinkFIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pineappleDrinkFIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pineappleDrinkFIELDActionPerformed

    private void porkSisigFIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porkSisigFIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_porkSisigFIELDActionPerformed

    private void checkOutBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutBTNActionPerformed
        SubClass price = new SubClass();
        
        double xTax, xSubtotal, xTotal;
        
        price.plainRiceM = price.priceplainRiceM * Double.parseDouble(plainRiceFIELD.getText());
        price.javaRiceM = price.pricejavaRiceM * Double.parseDouble(javaRiceFIELD.getText());
        price.barbequeM = price.pricebarbequeM * Double.parseDouble(barbequeFIELD.getText());
        price.porkSisigM = price.priceporkSisigM * Double.parseDouble(porkSisigFIELD.getText());
        price.liempoM = price.priceliempoM * Double.parseDouble(liempoFIELD.getText());
        
        price.spriteD = price.pricespriteD * Double.parseDouble(spriteFIELD.getText());
        price.cokeD = price.pricecokeD * Double.parseDouble(cokeFIELD.getText());
        price.icedTD = price.priceicedTD * Double.parseDouble(icedTeaFIELD.getText());
        price.pineappleD = price.pricepineappleD * Double.parseDouble(pineappleDrinkFIELD.getText());
        price.rootBeerD = price.pricerootBeerD * Double.parseDouble(rootBeerFIELD.getText());
        
        xSubtotal = price.getAmount();
        xTax = price.actTax(xSubtotal);
        xTotal = xTax + xSubtotal;
        
        String Ttax = String.format("₱%.2f", xTax);
        taxFIELD.setText(Ttax);   
        
        String subTotal = String.format("₱%.2f", xSubtotal);
        subTotalFIELD.setText(subTotal);
        
        String Ttotal = String.format("₱%.2f", xTotal);
        totalFIELD.setText(Ttotal);
        
        String meal = String.format("₱%.2f", price.meals);
        CostofMealFIELD.setText(meal);
        
        String ref = String.format("₱%.2f", price.refreshments);
        CostofDrinksField.setText(ref);
        
        String totalcost = String.format("₱%.2f", price.totalMD);
        totalCostMadeFIELD.setText(totalcost);
    }//GEN-LAST:event_checkOutBTNActionPerformed

    private void reciptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reciptActionPerformed
       
        Calendar can = Calendar.getInstance();
        can.getTime();
       
        SimpleDateFormat w = new SimpleDateFormat("HH:mm:ss");
        w.format(can.getTime());
        
        SimpleDateFormat e = new SimpleDateFormat("dd:MM:yyyy");
        e.format(can.getTime());
        
        recieptDisplay.append("\tRestaurant Management System\n\n" +
                "*************************************************************\n\n" +
                "List of Ordered Meals:\t\t" + CostofMealFIELD.getText()+"\n\n"+
                "List of Ordered Drinks\t\t" + CostofDrinksField.getText()+"\n\n"+
                "Total Cost Without Tax:\t\t"+ totalCostMadeFIELD.getText()+"\n\n"+
                "*************************************************************\n\n"+
                "Tax:\t\t\t\t"+ taxFIELD.getText()+ "\n\n"+
                "Subtotal:\t\t\t"+ subTotalFIELD.getText()+ "\n\n"+
                "Total:\t\t\t\t"+ totalFIELD.getText()+ "\n\n" +
                "*************************************************************\n\n"+
                "Date:\t\t\t\t" + e.format(can.getTime()) + "\n\n" +
                "Time:\t\t\t\t" + w.format(can.getTime())+ "\n\n" +
                "\t\t THANK YOU!");
    }//GEN-LAST:event_reciptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReyesBarbs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReyesBarbs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReyesBarbs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReyesBarbs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReyesBarbs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CostofDrinksField;
    private javax.swing.JTextField CostofMealFIELD;
    private javax.swing.JLabel barbeque;
    private javax.swing.JTextField barbequeFIELD;
    private javax.swing.JButton checkOutBTN;
    private javax.swing.JButton clearAllBTN;
    private javax.swing.JLabel coke;
    private javax.swing.JTextField cokeFIELD;
    private javax.swing.JLabel costofDrinks;
    private javax.swing.JLabel costofMeal;
    private javax.swing.JPanel costsPNL;
    private javax.swing.JLabel drinkTITLE;
    private javax.swing.JLabel icedTea;
    private javax.swing.JLabel icedTea1;
    private javax.swing.JLabel icedTea2;
    private javax.swing.JLabel icedTea3;
    private javax.swing.JLabel icedTea4;
    private javax.swing.JLabel icedTea5;
    private javax.swing.JTextField icedTeaFIELD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel javaRice;
    private javax.swing.JTextField javaRiceFIELD;
    private javax.swing.JLabel liempo;
    private javax.swing.JTextField liempoFIELD;
    private javax.swing.JPanel mealPNL;
    private javax.swing.JLabel mealsTITLE;
    private javax.swing.JLabel pineappleDrink;
    private javax.swing.JTextField pineappleDrinkFIELD;
    private javax.swing.JLabel plainRice;
    private javax.swing.JLabel plainRice1;
    private javax.swing.JLabel plainRice2;
    private javax.swing.JLabel plainRice3;
    private javax.swing.JLabel plainRice4;
    private javax.swing.JLabel plainRice5;
    private javax.swing.JTextField plainRiceFIELD;
    private javax.swing.JLabel porkSisig;
    private javax.swing.JTextField porkSisigFIELD;
    private java.awt.TextArea recieptDisplay;
    private javax.swing.JButton recipt;
    private javax.swing.JPanel reciptBTN;
    private javax.swing.JPanel refreshmentPNL;
    private javax.swing.JLabel rootBeer;
    private javax.swing.JTextField rootBeerFIELD;
    private javax.swing.JLabel sprite;
    private javax.swing.JTextField spriteFIELD;
    private javax.swing.JTextField subTotalFIELD;
    private javax.swing.JLabel subTotalLabel;
    private javax.swing.JTextField taxFIELD;
    private javax.swing.JLabel taxLabel;
    private javax.swing.JTextField totalCostMadeFIELD;
    private javax.swing.JTextField totalFIELD;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JPanel totalPNL;
    private javax.swing.JLabel totalcostMade;
    // End of variables declaration//GEN-END:variables
}
